### ISSUE TITLE
it doesn't work now

### ISSUE THREAD

**Issue by longweiyu** [xixia123/obsidian-transfer-latex-from-gpt#2]
the is no errors in console but it doesn't work

**Comment by xixia123** [comment]
I have just discovered that it has been launched in the community plugin marketplace. Thank you very much for your usage. I have just conducted a test. When you paste GPT's response into your Obsidian notes, please right-click and use the plain text format for pasting, and then apply this plugin. Kindly attempt this again, and if any issues persist, please feel free to share the problematic text with me.

**Comment by longweiyu** [comment]
Hello xixia123 I have used it for quite a long time. Your plugin is the best solution for Obsidian (Chatgpt) Markdown and Latex users. The problem is solved by your suggestion. Thank you!

**Comment by xixia123** [comment]
I'm very glad to hear that I could help you!

**Comment by longweiyu** [comment]
Hi xixia123, I find the reason is Obsidian automatically reforms the text for converting HTML to MD, so Setting->Editor-> Close Convert pasted HTML to Markdown button is better. Then you don't need to right click everytime. Maybe you can add this notice in the frontpage.

**Comment by xixia123** [comment]
Thank you very much for your help! The update has been completed.
